// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBon1FXnL5QThq7I478uhgD0DiWSCMxsLo',
    appId: '1:527629004129:web:c076d88577e3eab35ce920',
    messagingSenderId: '527629004129',
    projectId: 'fir-crud2-fef02',
    authDomain: 'fir-crud2-fef02.firebaseapp.com',
    storageBucket: 'fir-crud2-fef02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpQaXQdozqUYb3u7Kjr1fdR8S0WHph-Tc',
    appId: '1:527629004129:android:8531f8a6ad25c5d15ce920',
    messagingSenderId: '527629004129',
    projectId: 'fir-crud2-fef02',
    storageBucket: 'fir-crud2-fef02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy0oKESIgaHbxxD52_U8GnQWimdPhYYVM',
    appId: '1:527629004129:ios:bc3355f0888d30e05ce920',
    messagingSenderId: '527629004129',
    projectId: 'fir-crud2-fef02',
    storageBucket: 'fir-crud2-fef02.appspot.com',
    iosClientId: '527629004129-mhcrhglh9q0spiutdc751pimra85lqt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.imagenesai1sql',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy0oKESIgaHbxxD52_U8GnQWimdPhYYVM',
    appId: '1:527629004129:ios:0ed7267feeefc7905ce920',
    messagingSenderId: '527629004129',
    projectId: 'fir-crud2-fef02',
    storageBucket: 'fir-crud2-fef02.appspot.com',
    iosClientId: '527629004129-vi9vi7dian8i9fdiq7dqckp7e8f3sqp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.imagenesai1sql.RunnerTests',
  );
}
